### ISSUE TITLE
Script breaks here if File resource has a source parameter.

### ISSUE THREAD

**Issue by Houlistonm** [alexharv074/create_specs#9]
https://github.com/alexharv074/create_specs/blob/d81a8bbb12243888f7860af4c149bdc38c330a9c/create_specs.rb#L300

I'm not a ruby developer, but I moved the line after the test for content not nil.
thank you for a great utility.

**Comment by alexharv074** [comment]
Great. I agree with your fix. Try now?

**Comment by Houlistonm** [comment]
Thank you Alex,

It is hard for me to supply a lot of information - I work on a network that
has no connection to the internet, so everything has to be re-typed.
I really appreciate the utility.
Mark.

**Comment by Houlistonm** [comment]
Give me a few min to test, I have to incorporate a number of local changes
to test ...
We are required to follow https://github.com/bbatsov/ruby-style-guide here.

**Comment by Houlistonm** [comment]
works like a charm, thank you.

**Comment by alexharv074** [comment]
Oh haha. I am sure I am not completely compliant with the Ruby Style Guide. If there's anything causing you problems and you wanted to send a fix I'd be happy to look at your Rubocop config. Feel free to let me know if you think it could do with any new features. It is still evolving as a find more and more uses for it! Best wishes,
